#!/usr/bin/env bash
# Refresh this directory from the live system. Read-only with respect to
# /etc, /var and the overlay: it only writes inside gentoo/.
#
# The rsync calls use --delete, so entries removed from the system are removed
# here too. That is the point (the directory is a mirror, not an archive), and
# git keeps the removals visible and reversible.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

# /etc/portage. gnupg/ holds the binhost verification keyring and its
# passphrase, so it stays on the host. make.profile is a symlink into
# /var/db/repos/gentoo; the target is recorded in ./profile instead.
rsync -rlpt --delete \
	--exclude='gnupg/' \
	--exclude='make.profile' \
	--exclude='*~' \
	/etc/portage/ "${here}/portage/"

# Local overlay. Manifest files are regenerated by "ebuild <file> manifest",
# and md5-cache is a build artifact.
rsync -rlpt --delete \
	--exclude='Manifest' \
	--exclude='metadata/md5-cache/' \
	/var/db/repos/localrepo/ "${here}/localrepo/"

# Explicitly installed package set.
install -m644 /var/lib/portage/world "${here}/world"

# Selected profile, as "eselect profile" names it.
readlink -f /etc/portage/make.profile \
	| sed 's|.*/profiles/||' > "${here}/profile"

printf 'synced /etc/portage, localrepo, world and profile into %s\n' "${here}"
